import { disclaimer } from '../app.js';

export async function renderAbout(root) {
  root.innerHTML = `<section class="page-head"><div><h1>Method & limitations</h1><p class="muted">A transparent explanation of this low-cost optical visual screening workflow.</p></div></section>
    <article class="card"><h2>Visual screening pipeline</h2><div class="method-diagram" aria-label="Sample filtration through image analysis to visual screening results"><div class="method-step">Water sample<br>and filter</div><i class="arrow">→</i><div class="method-step">Controlled camera<br>image</div><i class="arrow">→</i><div class="method-step">OpenCV segmentation<br>and measurements</div><i class="arrow">→</i><div class="method-step">Optical estimation<br>and review</div></div><p>The system combines image preprocessing, segmentation, contour measurements, colour and texture features, and rule-based or machine-learning visual categories. It reports particles that visually resemble microplastics as <strong>suspected microplastic</strong> results.</p></article>
    <section class="grid two-col" style="margin-top:1rem"><article class="card"><h2>What it can do</h2><ul><li>Count and map visually distinct particles on a filter image.</li><li>Estimate visual shapes such as fibers, fragments, films, and pellets.</li><li>Estimate size after calibration with a known-distance reference.</li><li>Compare optical screening trends across locally stored samples.</li><li>Record reviewed particle classes to improve a local training dataset.</li></ul></article><article class="card"><h2>What it cannot do</h2><ul><li>It cannot chemically identify plastic or polymer type.</li><li>It cannot prove that a visually detected particle is plastic.</li><li>It cannot replace a laboratory quality-assurance process.</li><li>It cannot reliably quantify particles below the camera’s calibrated detection limit.</li></ul></article></section>
    <article class="card" style="margin-top:1rem"><h2>Limitations</h2><ul><li>Camera resolution constrains the minimum reliable detectable size.</li><li>Transparent particles are difficult to distinguish from the filter.</li><li>Dust, organic matter, filter fibres, and surface defects can produce false positives.</li><li>Lighting, focus, image compression, and changing camera distance affect segmentation.</li><li>Size estimates require calibration using the same imaging setup.</li><li>ML estimates depend on the quality, diversity, and verification of their training data.</li><li>Environmental samples are more complex than controlled laboratory images.</li></ul></article>
    <article class="card" style="margin-top:1rem"><h2>Recommended imaging setup</h2><ul><li>Use a dark, matte imaging chamber to reduce reflections.</li><li>Use diffused, consistent LED illumination rather than variable ambient light.</li><li>Fix the camera distance, focus, and filter position before calibration.</li><li>Capture multiple frames when possible to reduce sensor noise through median stacking.</li><li>Keep filters clean and document sample volume, pore size, and handling conditions.</li></ul></article>${disclaimer()}`;
}
