import { api } from '../api.js';
import { barChart, donutChart, scatterChart } from '../charts.js';
import { date, disclaimer, escapeHtml, navigate, number, toast } from '../app.js';

export async function renderSample(root, route) {
  const result = await api.sample(route.id);
  if (!result.analysis) { root.innerHTML = `<div class="card empty"><h2>No analysis yet</h2><p>This sample has no image analysis.</p><button id="reanalyze-empty">Re-analyse sample</button></div>`; root.querySelector('#reanalyze-empty').onclick = () => toast('Upload an image to this sample from New analysis.', true); return; }
  let { sample, analysis } = result;
  let view = 'original'; let page = 1; let sort = 'idx'; let direction = 1;
  const render = () => {
    root.innerHTML = `<section class="page-head"><div><h1>${escapeHtml(sample.name)}</h1><p class="muted">${escapeHtml(sample.location || 'No location')} · Created ${date(sample.created_at)}</p></div><div class="action-row"><button id="edit-meta" class="secondary">Edit</button><button id="reanalyze" class="secondary">Re-analyse</button><button id="export-csv" class="secondary">CSV</button><button id="export-json" class="secondary">JSON</button><button id="export-pdf" class="secondary">PDF</button><button id="print" class="secondary">Print</button><button id="delete" class="danger">Delete</button></div></section><div id="metadata-editor"></div>${analysis.mm_per_pixel === null ? '<p class="warning">Not calibrated — sizes shown in pixels. Create or select a calibration before relying on physical measurements.</p>' : ''}
    <section class="card"><h2>Screening summary</h2>${summary(analysis)}</section><section class="grid two-col" style="margin-top:1rem"><article class="card"><h2>Annotated visual result</h2><div class="tabs"><button class="${view === 'original' ? 'active' : ''}" data-view="original">Original</button><button class="${view === 'annotated' ? 'active' : ''}" data-view="annotated">Annotated</button><button class="${view === 'mask' ? 'active' : ''}" data-view="mask">Mask</button></div><div class="image-viewer" id="viewer">${viewer(analysis, view)}</div><div class="image-controls"><label>Annotated overlay <input id="overlay-range" type="range" min="0" max="100" value="55"></label><span class="muted">Wheel to zoom · drag to pan · click a box to select a particle</span></div></article><article class="card"><h2>Visual distributions</h2><h3>Shape category</h3>${donutChart([analysis.fibers, analysis.fragments, analysis.films, analysis.pellets, analysis.non_plastic], ['Fibers', 'Fragments', 'Films', 'Pellets', 'Non-plastic'])}<h3 style="margin-top:1rem">Size distribution (${analysis.mm_per_pixel === null ? 'px' : 'mm'})</h3>${histogram(analysis)}</article></section><section class="grid two-col" style="margin-top:1rem"><article class="card"><h2>Aspect ratio versus length</h2>${scatterChart(analysis.particles)}</article><article class="card"><h2>Confidence distribution</h2>${confidenceChart(analysis.particles)}</article></section><section class="card" style="margin-top:1rem"><div class="page-head"><div><h2>Particles</h2><p class="muted">Corrected classes are saved as verified labels for model training.</p></div><div class="filters"><input id="particle-search" placeholder="Search ID or colour"><select id="class-filter"><option value="">All classes</option>${['fiber','fragment','film','pellet','non_plastic'].map(name => `<option value="${name}">${name.replace('_',' ')}</option>`).join('')}</select><select id="label-filter"><option value="">All labels</option><option value="suspected_plastic">Suspected plastic</option><option value="non_plastic">Non-plastic</option></select><select id="size-filter"><option value="">All sizes</option><option value="small">Below 1 ${analysis.mm_per_pixel === null ? 'px' : 'mm'}</option><option value="large">At least 1 ${analysis.mm_per_pixel === null ? 'px' : 'mm'}</option></select></div></div><div id="particle-table"></div></section>${disclaimer()}`;
    attach(); renderTable();
  };
  const renderTable = () => {
    const search = root.querySelector('#particle-search')?.value.toLowerCase() || '';
    const className = root.querySelector('#class-filter')?.value || '';
    const label = root.querySelector('#label-filter')?.value || '';
    const size = root.querySelector('#size-filter')?.value || '';
    const unitLength = particle => particle.length_mm ?? particle.length_px;
    let rows = analysis.particles.filter(particle => (!search || `${particle.idx} ${particle.color_name}`.toLowerCase().includes(search)) && (!className || particle.shape_class === className) && (!label || particle.label === label) && (!size || (size === 'small' ? unitLength(particle) < 1 : unitLength(particle) >= 1)));
    rows = rows.sort((a, b) => (typeof a[sort] === 'string' ? a[sort].localeCompare(b[sort]) : (a[sort] ?? 0) - (b[sort] ?? 0)) * direction);
    const perPage = 15; const pages = Math.max(1, Math.ceil(rows.length / perPage)); page = Math.min(page, pages); const shown = rows.slice((page - 1) * perPage, page * perPage);
    root.querySelector('#particle-table').innerHTML = `<div class="table-wrap"><table class="table"><thead><tr>${[['idx','ID'],['shape_class','Class'],['label','Label'],['length_px',`Length (${analysis.mm_per_pixel === null ? 'px' : 'mm'})`],['width_px',`Width (${analysis.mm_per_pixel === null ? 'px' : 'mm'})`],['aspect_ratio','Aspect'],['circularity','Circularity'],['color_name','Colour'],['confidence','Confidence'],['verified','Correct class']].map(([key,title]) => `<th ${key === 'verified' ? '' : `data-sort="${key}"`} >${title}</th>`).join('')}</tr></thead><tbody>${shown.map(particleRow).join('')}</tbody></table></div><div class="pagination"><span>${rows.length} matching particles</span><span><button id="prev-page" class="secondary" ${page === 1 ? 'disabled' : ''}>Previous</button> Page ${page} of ${pages} <button id="next-page" class="secondary" ${page === pages ? 'disabled' : ''}>Next</button></span></div>`;
    root.querySelectorAll('[data-sort]').forEach(header => header.onclick = () => { const key = header.dataset.sort; direction = sort === key ? -direction : 1; sort = key; renderTable(); });
    root.querySelector('#prev-page').onclick = () => { page--; renderTable(); }; root.querySelector('#next-page').onclick = () => { page++; renderTable(); };
    root.querySelectorAll('.particle-correction').forEach(select => select.onchange = async () => { try { const particle = await api.correctParticle(select.dataset.id, select.value || null); const local = analysis.particles.find(item => item.id === particle.id); Object.assign(local, particle); toast('Verified class saved'); } catch (error) { toast(error.message, true); } });
  };
  const particleRow = particle => `<tr id="particle-${particle.id}"><td>${particle.idx}</td><td>${particle.shape_class.replace('_',' ')}</td><td>${particle.label.replace('_',' ')}</td><td>${measurement(particle.length_mm, particle.length_px)}</td><td>${measurement(particle.width_mm, particle.width_px)}</td><td>${number(particle.aspect_ratio,2)}</td><td>${number(particle.circularity,2)}</td><td>${particle.color_name}</td><td>${number(particle.confidence * 100,0)}%</td><td><select class="particle-correction" data-id="${particle.id}"><option value="">Unverified</option>${['fiber','fragment','film','pellet','non_plastic'].map(name => `<option value="${name}" ${particle.user_verified_class === name ? 'selected' : ''}>${name.replace('_',' ')}</option>`).join('')}</select></td></tr>`;
  const attach = () => {
    root.querySelectorAll('[data-view]').forEach(button => button.onclick = () => { view = button.dataset.view; render(); });
    root.querySelectorAll('.hotspot').forEach(box => box.onclick = () => { const row = root.querySelector(`#particle-${box.dataset.particle}`); row?.classList.add('selected-row'); row?.scrollIntoView({ behavior: 'smooth', block: 'center' }); setTimeout(() => row?.classList.remove('selected-row'), 1800); });
    root.querySelector('#overlay-range').oninput = event => { const overlay = root.querySelector('#annotation-overlay'); if (overlay) overlay.style.opacity = event.target.value / 100; };
    attachPanZoom(root.querySelector('#viewer'));
    ['particle-search','class-filter','label-filter','size-filter'].forEach(id => root.querySelector(`#${id}`).oninput = () => { page = 1; renderTable(); });
    root.querySelector('#edit-meta').onclick = () => editMetadata(root, sample, async values => { sample = await api.updateSample(sample.id, values); render(); });
    root.querySelector('#reanalyze').onclick = async event => { event.currentTarget.disabled = true; try { const next = await api.reanalyze(sample.id); analysis = next.analysis; toast('Analysis rerun with current settings'); render(); } catch (error) { toast(error.message, true); event.currentTarget.disabled = false; } };
    for (const type of ['csv','json','pdf']) root.querySelector(`#export-${type}`).onclick = () => window.open(api.exportUrl(sample.id, type), '_blank', 'noopener');
    root.querySelector('#print').onclick = () => print();
    root.querySelector('#delete').onclick = async () => { if (!confirm(`Delete ${sample.name} and its stored analysis files?`)) return; try { await api.deleteSample(sample.id); toast('Sample deleted'); navigate('/history'); } catch (error) { toast(error.message, true); } };
  };
  render();
}

function summary(analysis) { const items = [['Total particles',analysis.total_particles],['Suspected plastic',analysis.suspected_plastic],['Fibers',analysis.fibers],['Fragments',analysis.fragments],['Films',analysis.films],['Pellets',analysis.pellets],['Non-plastic',analysis.non_plastic],['Concentration',analysis.concentration_per_l === null ? '—' : `${number(analysis.concentration_per_l,1)}/L`],['Mean size',analysis.mean_length_mm === null ? '—' : `${number(analysis.mean_length_mm,3)} mm`],['Sample confidence',`${number(analysis.sample_confidence,0)}%`],['Min reliable size',analysis.min_reliable_size_mm === null ? '—' : `${number(analysis.min_reliable_size_mm,3)} mm`],['Processing time',`${number(analysis.processing_ms,0)} ms`]]; return `<div class="summary-grid">${items.map(([label,value]) => `<div class="summary-item"><span>${label}</span><b>${value}</b></div>`).join('')}</div>`; }
function viewer(analysis, view) { const url = type => api.imageUrl(analysis.id, type); const boxes = analysis.particles.map(particle => `<button class="hotspot" data-particle="${particle.id}" style="left:${particle.bbox_x / analysis.image_w * 100}%;top:${particle.bbox_y / analysis.image_h * 100}%;width:${particle.bbox_w / analysis.image_w * 100}%;height:${particle.bbox_h / analysis.image_h * 100}%" title="Particle ${particle.idx}"></button>`).join(''); if (view === 'original') return `<div class="image-stage"><img src="${url('original')}" alt="Original filter image"><img id="annotation-overlay" class="overlay-image" src="${url('annotated')}" alt="" style="opacity:.55">${boxes}</div>`; return `<div class="image-stage"><img src="${url(view)}" alt="${view} image"></div>`; }
function histogram(analysis) { const values = analysis.particles.map(particle => particle.length_mm ?? particle.length_px); const bins = analysis.mm_per_pixel === null ? [50,100,250,500,1000] : [0.2,.5,1,2,5]; const counts = Array(bins.length + 1).fill(0); values.forEach(value => counts[`${bins.findIndex(threshold => value < threshold)}` === '-1' ? bins.length : bins.findIndex(threshold => value < threshold)]++); const labels = [`<${bins[0]}`, ...bins.slice(1).map((value,index) => `${bins[index]}–${value}`), `>${bins.at(-1)}`]; return barChart(labels, counts, { label: 'particle size distribution' }); }
function confidenceChart(particles) { const bins = [0,0,0,0,0]; particles.forEach(particle => bins[Math.min(4,Math.floor(particle.confidence * 5))]++); return barChart(['0–20%','20–40%','40–60%','60–80%','80–100%'], bins, { label: 'confidence distribution' }); }
function measurement(mm, px) { return mm === null || mm === undefined ? `${number(px,1)} px` : `${number(mm,3)} mm`; }
function editMetadata(root, sample, onSave) { const host = root.querySelector('#metadata-editor'); host.innerHTML = `<form id="metadata-form" class="card form-grid" style="margin-bottom:1rem"><div class="field"><label>Name<input name="name" required value="${escapeHtml(sample.name)}"></label></div><div class="field"><label>Location<input name="location" value="${escapeHtml(sample.location || '')}"></label></div><div class="field"><label>Volume (mL)<input name="volume_ml" type="number" step="any" value="${sample.volume_ml || ''}"></label></div><div class="field"><label>Filter pore (µm)<input name="filter_pore_um" type="number" step="any" value="${sample.filter_pore_um || ''}"></label></div><div class="field full"><label>Notes<textarea name="notes">${escapeHtml(sample.notes || '')}</textarea></label></div><div class="form-actions"><button>Save metadata</button><button type="button" class="secondary" id="cancel-edit">Cancel</button></div></form>`; host.querySelector('#cancel-edit').onclick = () => host.innerHTML = ''; host.querySelector('form').onsubmit = async event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); for (const key of ['volume_ml','filter_pore_um']) data[key] = data[key] ? Number(data[key]) : null; try { await onSave(data); toast('Sample metadata updated'); } catch (error) { toast(error.message, true); } }; }
function attachPanZoom(viewer) { const stage = viewer.querySelector('.image-stage'); if (!stage) return; let scale = 1, x = 0, y = 0, start; const paint = () => stage.style.transform = `translate(${x}px,${y}px) scale(${scale})`; viewer.onwheel = event => { event.preventDefault(); scale = Math.max(1, Math.min(4, scale + (event.deltaY < 0 ? .15 : -.15))); paint(); }; viewer.onpointerdown = event => { start = { x:event.clientX-x, y:event.clientY-y }; stage.classList.add('dragging'); viewer.setPointerCapture(event.pointerId); }; viewer.onpointermove = event => { if (!start) return; x=event.clientX-start.x; y=event.clientY-start.y; paint(); }; viewer.onpointerup = () => { start = null; stage.classList.remove('dragging'); }; }
